

const 
menu = [
  {
    id: 1,
    title: 'BA in English',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on literature, language, and writing, offering courses in literary analysis, creative writing, and linguistics. It develops critical thinking and communication skills, preparing students for diverse careers in fields like education, publishing, and media.`,
  },
  {
    id: 2,
    title: 'BA in Sociology',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program examines society, culture, and social behavior, offering courses in social theory, research methods, and cultural studies. It develops analytical and interpersonal skills, preparing students for careers in social work, research, community development, and public policy.`,
  },
  {
    id: 3,
    title: 'BA in Political Science',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on political systems, governance, and public policies, offering courses in political theory, international relations, and comparative politics. It develops critical thinking and analytical skills, preparing students for careers in government, diplomacy, law, and international organizations.`,
  },
  {
    id: 4,
    title: 'BA in Psychology',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program explores human behavior, mental processes, and social interactions, offering courses in cognitive psychology, developmental psychology, and abnormal psychology. It helps develop critical thinking and research skills, preparing students for careers in counseling, mental health, research, and human resources.`,
  },
  {
    id: 5,
    title: 'BA in History',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program examines historical events, cultures, and their impact on the present, offering courses in world history, cultural studies, and historical research methods. It develops analytical and research skills, preparing students for careers in education, archival research, museums, and cultural heritage.`,
  },
  {
    id: 6,
    title: 'BA in Fine Arts',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on the visual arts, including painting, sculpture, and creative expression. It offers courses in art history, studio practice, and design, helping students develop their artistic skills and critical thinking. Graduates are prepared for careers in art, design, education, and the creative industries.`,
  },
  {
    id: 7,
    title: 'BA in Journalism',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on media, reporting, and communication, offering courses in news writing, digital journalism, and media ethics. It develops skills in storytelling, research, and critical analysis, preparing students for careers in journalism, broadcasting, public relations, and digital media.


`,
  },
  {
    id: 8,
    title: 'BA in International Relations',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program explores global politics, diplomacy, and international affairs, offering courses in international law, conflict resolution, and global economic systems. It develops critical thinking and analytical skills, preparing students for careers in diplomacy, international organizations, government, and global advocacy.`,
  },
  {
    id: 9,
    title: 'BA in Linguistics',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on the scientific study of language, offering courses in phonetics, syntax, semantics, and sociolinguistics. It develops analytical and research skills, preparing students for careers in education, translation, research, language technology, and language policy.`,
  },
  {
    id: 10,
    title: 'BA in Cultural Studies',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program examines cultural dynamics, traditions, and their impact on society, offering courses in media studies, anthropology, and cultural theory. It develops critical thinking and research skills, preparing students for careers in cultural analysis, media, community development, and education.`,
  },

  {
    id: 11,
    title: 'Bachelor of Commerce (B.Com)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on accounting, finance, business law, and economics, preparing students for careers in financial services, accounting, and business management.`,
},
{
    id: 12,
    title: 'Bachelor of Business Administration (BBA)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program covers business management, leadership, marketing, and organizational behavior, preparing students for leadership roles in various business sectors.`,
},
{
    id: 13,
    title: 'Bachelor of Business Administration in Financial Management (BBA-FM)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program specializes in financial planning, risk management, and investment analysis, equipping students with the knowledge and skills for careers in finance and banking.`,
},
{
    id: 14,
    title: 'Bachelor of Accounting and Finance (BAF)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on accounting principles, financial reporting, and auditing, preparing students for roles in accounting, auditing, and financial management.`,
},
{
    id: 15,
    title: 'Bachelor of Commerce in Computer Applications (B.Com-CA)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program combines commerce with computer science, focusing on business technology, software applications, and the use of technology in business operations.`,
},
{
    id: 16,
    title: 'Bachelor of Business Administration in Marketing (BBA-Marketing)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program specializes in marketing strategies, consumer behavior, and digital marketing, preparing students for roles in marketing management, advertising, and brand management.`,
},
{
    id: 17,
    title: 'Bachelor of Financial Market (BFM)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on financial markets, stock trading, and portfolio management, providing students with the skills needed to analyze and manage investments in the financial sector.`,
},
{
    id: 18,
    title: 'Bachelor of Business Administration in International Business (BBA-IB)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program covers global business practices, international trade, and cross-cultural management, preparing students for careers in international business, trade, and global commerce.`,
},
{
    id: 19,
    title: 'Bachelor of Hotel Management (BHM)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program focuses on hospitality, hotel operations, and tourism management, preparing students for leadership roles in the hospitality and tourism industries.`,
},
{
    id: 20,
    title: 'Bachelor of Commerce in Taxation (B.Com-Taxation)',
    category: 'Arts/Comm',
    duration: "3 OR 4 years",
    img: 'https://images.unsplash.com/photo-1473186505569-9c61870c11f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80',
    desc: `This program specializes in tax planning, tax laws, and corporate taxation, preparing students for careers in tax consulting, corporate taxation, and financial advisory services.`,
},

{
  id: 21,
  title: 'Bachelor of Design (B.Des)',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program covers various aspects of design, including visual communication, graphic design, and product design. Students will learn creative problem-solving, design theory, and hands-on design skills.`,
},
{
  id: 22,
  title: 'Bachelor of Fine Arts (BFA)',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program focuses on the creative and technical aspects of art, offering courses in painting, sculpture, and printmaking. It prepares students for careers in fine art, galleries, or teaching.`,
},
{
  id: 23,
  title: 'Bachelor of Interior Design',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program prepares students to design functional, aesthetically pleasing interiors for homes, offices, and commercial spaces. It covers spatial planning, materials, and color theory.`,
},
{
  id: 24,
  title: 'Bachelor of Fashion Design',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program focuses on fashion design, garment construction, and textile technology. Students learn about the fashion industry, trends, and how to create and market clothing lines.`,
},
{
  id: 25,
  title: 'Bachelor of Graphic Design',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program focuses on visual communication, teaching students how to use design software, typography, and color theory to create graphic content for various media such as advertisements, websites, and branding.`,
},
{
  id: 26,
  title: 'Bachelor of Animation and Multimedia',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program focuses on animation, video editing, and multimedia production. Students will learn 2D and 3D animation, film production, and multimedia technologies used in entertainment, gaming, and advertising.`,
},
{
  id: 27,
  title: 'Bachelor of Product Design',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program covers the design and development of products from concept to production. Students will learn about materials, ergonomics, and product development processes for creating consumer goods.`,
},
{
  id: 28,
  title: 'Bachelor of Web Design',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program focuses on web design principles, user experience (UX), and front-end development, teaching students how to create functional and visually appealing websites for various devices.`,
},
{
  id: 29,
  title: 'Bachelor of Industrial Design',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program covers the design of industrial products, such as tools, machines, and vehicles. Students will focus on innovation, sustainability, and materials science while developing functional and aesthetic designs.`,
},
{
  id: 30,
  title: 'Bachelor of Game Design',
  category: 'Design',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program teaches students how to design and develop interactive games, from concept to creation. It includes courses on game mechanics, programming, storytelling, and digital art in the gaming industry.`,
},
{
  id: 31,
  title: 'Bachelor of Medicine, Bachelor of Surgery (MBBS)',
  category: 'Health',
  duration: "5-6 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program provides the essential education and training required for becoming a medical doctor, covering anatomy, physiology, pathology, and clinical practice. It prepares students for clinical internships and medical practice.`,
},
{
  id: 32,
  title: 'Bachelor of Nursing (BN)',
  category: 'Health',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program prepares students to provide patient-centered care in diverse healthcare settings. It includes training in anatomy, pharmacology, clinical practice, and nursing ethics, equipping graduates to work as registered nurses in hospitals, clinics, and community health organizations.`
},

{
  id: 33,
  title: 'Bachelor of Physiotherapy (BPT)',
  category: 'Health',
  duration: "4.5 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program focuses on physical therapy, rehabilitation, and improving mobility in patients with physical impairments. It includes hands-on clinical training in healthcare settings.`,
},
{
  id: 34,
  title: 'Bachelor of Public Health (BPH)',
  category: 'Health',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program teaches students about public health systems, epidemiology, and preventive health strategies. Graduates often work in health education, policy-making, or community health settings.`,
},
{
  id: 35,
  title: 'Bachelor of Dental Surgery (BDS)',
  category: 'Health',
  duration: "4-5 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program provides training in diagnosing and treating dental and oral health issues. It includes clinical practice in dental surgery and prepares graduates for careers as dentists.`,
},
{
  id: 36,
  title: 'Bachelor of Medical Laboratory Science (BMLS)',
  category: 'Health',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program focuses on laboratory-based diagnostics and research. Students learn techniques for analyzing biological samples and assisting in disease diagnosis.`,
},
{
  id: 37,
  title: 'Bachelor of Biomedical Science',
  category: 'Health',
  duration: "3-4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program delves into the scientific basis of human health, studying cellular and molecular processes. It is ideal for careers in medical research, diagnostics, or biotech industries.`,
},
{
  id: 38,
  title: 'Bachelor of Optometry (B.Optom)',
  category: 'Health',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program trains students in eye care, vision therapy, and optometry practices. Graduates often work in optometry clinics, hospitals, or research roles related to visual sciences.`,
},
{
  id: 39,
  title: 'Bachelor of Veterinary Science (B.V.Sc)',
  category: 'Health',
  duration: "5-6 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program prepares students for careers in veterinary medicine, focusing on animal health, surgery, and nutrition. It includes both clinical training and research opportunities.`,
},
{
  id: 40,
  title: 'Bachelor of Occupational Therapy (BOT)',
  category: 'Health',
  duration: "4-5 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program trains students to help patients regain independence in daily life through therapeutic techniques. Graduates work in hospitals, rehabilitation centers, and community health settings.`,
},
{
  id: 41,
  title: 'Bachelor of Science in Nutrition and Dietetics (BSc-ND)',
  category: 'Health',
  duration: "3-4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program focuses on the role of nutrition in health and disease prevention. Graduates work as dietitians, nutritionists, or health advisors in clinics, hospitals, and wellness industries.`,
},
{
  id: 42,
  title: 'Bachelor of Science in Anesthesia Technology (BSc-AT)',
  category: 'Health',
  duration: "3-4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program trains students in the administration and management of anesthesia during surgeries and medical procedures. Graduates often work in surgical teams or as anesthesia technologists in hospitals.`,
},
{
  id: 43,
  title: 'Bachelor of Science in Radiology and Imaging Technology (BSc-RIT)',
  category: 'Health',
  duration: "3-4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program focuses on diagnostic imaging techniques such as X-ray, MRI, and ultrasound. Graduates work as radiologic technologists or imaging specialists in healthcare facilities.`,
},
{
  id: 44,
  title: 'Bachelor of Science in Emergency Medical Services (BSc-EMS)',
  category: 'Health',
  duration: "3-4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program prepares students for critical roles in emergency healthcare, focusing on pre-hospital care, trauma response, and disaster management. Graduates often work as paramedics or emergency medical technicians.`,
},
{
  id: 45,
  title: 'Bachelor of Science in Cardiac Perfusion Technology (BSc-CPT)',
  category: 'Health',
  duration: "3-4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program trains students in operating heart-lung machines during cardiac surgeries. Graduates work in hospitals as cardiac perfusionists, assisting in critical care procedures.`,
},
{
  id: 46,
  title: 'Bachelor of Science in Clinical Research (BSc-CR)',
  category: 'Health',
  duration: "3-4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program provides training in the design and conduct of clinical trials for new drugs and therapies. Graduates often work in pharmaceutical companies, research organizations, or healthcare institutions.`,
},
{
  id: 47,
  title: 'Bachelor of Science in Audiology and Speech-Language Pathology (BASLP)',
  category: 'Health',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
  desc: `This program focuses on diagnosing and treating hearing disorders and speech-language impairments. Graduates work as audiologists or speech therapists in clinics and hospitals.`,
},

{
  id: 48,
  title: 'Bachelor of Technology in Computer Science (B.Tech-CS)',
  category: 'Engg/IT',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1076&q=80',
  desc: `This program focuses on computer programming, software development, and data structures. Students gain expertise in algorithms, operating systems, and computer networks, preparing them for careers in software engineering, data analysis, and IT consulting.`,
},
{
  id: 49,
  title: 'Bachelor of Technology in Information Technology (B.Tech-IT)',
  category: 'Engg/IT',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1076&q=80',
  desc: `This program emphasizes IT infrastructure, database management, and cybersecurity. It prepares students for roles in systems analysis, cloud computing, and IT project management through hands-on learning and internships.`,
},
{
  id: 50,
  title: 'Bachelor of Engineering in Mechanical Engineering (B.E. Mech)',
  category: 'Engg/IT',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program covers design, manufacturing, and maintenance of mechanical systems. It equips students with problem-solving skills for careers in automotive, aerospace, energy, and robotics industries.`,
},
{
  id: 51,
  title: 'Bachelor of Technology in Electronics and Communication Engineering (B.Tech-ECE)',
  category: 'Engg/IT',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1591799265444-d66432b91588?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1780&q=80',
  desc: `This program focuses on electronic circuits, communication systems, and signal processing. Students are prepared for roles in telecommunications, embedded systems, and electronics design.`,
},
{
  id: 52,
  title: 'Bachelor of Technology in Artificial Intelligence and Data Science (B.Tech-AI & DS)',
  category: 'Engg/IT',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1647427060118-4911c9821b82?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program integrates artificial intelligence, machine learning, and big data technologies. Students develop analytical and computational skills, preparing them for careers in AI development, data analytics, and research.`,
},
{
  id: 53,
  title: 'Bachelor of Technology in Civil Engineering (B.Tech-Civil)',
  category: 'Engg/IT',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1487491424367-7571f9afbb30?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80',
  desc: `This program emphasizes construction, design, and maintenance of infrastructure projects. It equips students for careers in urban planning, structural engineering, and environmental consulting.`,
},
{
  id: 54,
  title: 'Bachelor of Technology in Electrical Engineering (B.Tech-EE)',
  category: 'Engg/IT',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program covers electrical circuits, power systems, and control engineering. It prepares students for careers in renewable energy, power generation, and electrical system design.`,
},
{
  id: 55,
  title: 'Bachelor of Technology in Aerospace Engineering (B.Tech-Aerospace)',
  category: 'Engg/IT',
  duration: "4 years",
  img: 'https://images.unsplash.com/photo-1457364847821-58861bbda116?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program focuses on aircraft and spacecraft design, aerodynamics, and propulsion systems. It prepares students for roles in aviation, defense, and space exploration industries.`,
},
{
  id: 56,
  title: 'Bachelor of Science in Computer Science (B.Sc-CS)',
  category: 'Engg/IT',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1076&q=80',
  desc: `This program focuses on computer programming, software development, and systems analysis. Students learn about algorithms, operating systems, and data management, preparing them for careers in IT, software engineering, and data analytics.`,
},
{
  id: 57,
  title: 'Bachelor of Science in Information Technology (B.Sc-IT)',
  category: 'Engg/IT',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1076&q=80',
  desc: `This program covers IT systems, database management, and cybersecurity. Students gain hands-on experience in IT infrastructure and project management, preparing them for roles in IT consultancy and systems administration.`,
},
{
  id: 58,
  title: 'Bachelor of Science in Data Science (B.Sc-DS)',
  category: 'Engg/IT',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1518186233392-c232efbf2373?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80',
  desc: `This program focuses on big data analysis, machine learning, and statistical modeling. It prepares students to tackle real-world problems in business, healthcare, and finance through data-driven solutions.`,
},
{
  id: 59,
  title: 'Bachelor of Science in Artificial Intelligence (B.Sc-AI)',
  category: 'Engg/IT',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1647427060118-4911c9821b82?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program dives deep into AI techniques, natural language processing, and robotics. Students develop the skills needed for cutting-edge research and applications in AI development.`,
},
{
  id: 60,
  title: 'Bachelor of Science in Cybersecurity (B.Sc-Cybersecurity)',
  category: 'Engg/IT',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1518186233392-c232efbf2373?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80',
  desc: `This program equips students with skills to protect networks, systems, and data from cyber threats. It includes courses in ethical hacking, digital forensics, and network security.`,
},
{
  id: 61,
  title: 'Bachelor of Science in Software Engineering (B.Sc-SE)',
  category: 'Engg/IT',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1076&q=80',
  desc: `This program focuses on designing, developing, and maintaining software systems. Students gain expertise in programming languages, software architecture, and project management.`,
},
{
  id: 62,
  title: 'Bachelor of Science in Electronics (B.Sc-Electronics)',
  category: 'Engg/IT',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program covers the principles of electronic systems, circuits, and devices. It prepares students for roles in semiconductor design, telecommunications, and consumer electronics.`,
},
{
  id: 63,
  title: 'Bachelor of Science in Robotics (B.Sc-Robotics)',
  category: 'Engg/IT',
  duration: "3 OR 4 years",
  img: 'https://images.unsplash.com/photo-1647427060118-4911c9821b82?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  desc: `This program delves into robot design, automation systems, and AI integration. It prepares students for innovative roles in automation, manufacturing, and advanced robotics.`,
}
,
{
  id: 64,
  title: 'Master of Commerce (M.Com)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `The M.Com program focuses on advanced concepts in accounting, economics, and business law, providing a deep understanding of financial management and business practices. Graduates are prepared for roles in accounting, finance, and research.`,
},
{
  id: 65,
  title: 'Master of Business Administration (MBA)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `The MBA program provides advanced knowledge in business management, leadership, marketing, and strategic decision-making. Graduates can pursue managerial and executive roles across various industries.`,
},
{
  id: 66,
  title: 'Master of Business Administration in Financial Management (MBA-FM)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program specializes in financial planning, risk management, and investment strategies. It prepares graduates for careers in corporate finance, financial analysis, and wealth management.`,
},
{
  id: 67,
  title: 'Master of Accounting and Finance (M.A.F.)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program offers in-depth knowledge of accounting principles, financial reporting, and auditing. Graduates are well-suited for roles in accounting, auditing, taxation, and financial management.`,
},
{
  id: 68,
  title: 'Master of Commerce in Computer Applications (M.Com-CA)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program integrates commerce with technology, focusing on the application of computer science to business processes. Graduates are equipped for careers in business analytics, software development, and IT management.`,
},
{
  id: 69,
  title: 'Master of Business Administration in Marketing (MBA-Marketing)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program specializes in advanced marketing strategies, consumer behavior, brand management, and digital marketing. Graduates can pursue careers in marketing management, brand consultancy, and advertising.`,
},
{
  id: 70,
  title: 'Master of Financial Markets (MFM)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program focuses on financial markets, stock trading, and investment analysis. It prepares graduates for roles in investment banking, portfolio management, and financial analysis.`,
},
{
  id: 71,
  title: 'Master of Business Administration in International Business (MBA-IB)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program provides knowledge of global business practices, international trade, and cross-cultural management. Graduates are ready for leadership positions in international trade, global business operations, and multinational companies.`,
},
{
  id: 72,
  title: 'Master of Hotel Management (MHM)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `The MHM program focuses on hospitality management, hotel operations, and tourism industry practices. Graduates can pursue careers in luxury hotel management, tourism planning, and hospitality services.`,
},
{
  id: 73,
  title: 'Master of Commerce in Taxation (M.Com-Taxation)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program specializes in corporate taxation, tax planning, and business tax laws. Graduates can work as tax consultants, tax analysts, and tax managers in large corporations or consultancy firms.`,
},
{
  id: 74,
  title: 'Doctor of Philosophy in Commerce (Ph.D.-Commerce)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `The Ph.D. in Commerce focuses on advanced research in accounting, finance, economics, and business law. Graduates often pursue careers in academia or high-level consultancy in the commerce sector.`,
},
{
  id: 75,
  title: 'Doctor of Philosophy in Business Administration (Ph.D.-Business Admin)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `This research-oriented program delves into advanced business theories, organizational behavior, leadership, and strategic decision-making. Graduates are equipped to teach at universities or consult for large businesses.`,
},
{
  id: 76,
  title: 'Doctor of Philosophy in Accounting and Finance (Ph.D.-Accounting & Finance)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `This program offers specialized research in accounting principles, financial reporting, and corporate finance. Graduates are prepared to conduct research, teach at the university level, or lead in corporate finance roles.`,
},
{
  id: 77,
  title: 'Doctor of Philosophy in Marketing (Ph.D.-Marketing)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `The Ph.D. in Marketing focuses on advanced research in consumer behavior, branding, and marketing strategies. Graduates contribute to academic literature or work in strategic marketing roles at high levels.`,
},
{
  id: 78,
  title: 'Doctor of Philosophy in International Business (Ph.D.-International Business)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `This program offers advanced research opportunities in global business management, international trade, and cross-cultural management. Graduates are prepared for academic positions or strategic roles in multinational corporations.`,
},
{
  id: 79,
  title: 'Doctor of Philosophy in Hotel Management (Ph.D.-Hotel Management)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `This program focuses on research in hospitality management, tourism, and the operational aspects of the hotel industry. Graduates can pursue careers in academia or high-level management positions within the hospitality industry.`,
},
{
  id: 80,
  title: 'Doctor of Philosophy in Taxation (Ph.D.-Taxation)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `This program focuses on advanced research in corporate tax laws, tax policies, and global taxation practices. Graduates are prepared for research positions, teaching, or consultancy in tax law and policy.`,
}
,
{
  id: 81,
  title: 'Master of Technology (M.Tech) in Computer Science and Engineering',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program focuses on advanced topics in computer science such as software engineering, algorithms, and data structures. It prepares graduates for careers in software development, IT consulting, and research.`,
},
{
  id: 82,
  title: 'Master of Engineering (M.Eng) in Electrical Engineering',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program offers advanced studies in electrical systems, circuit design, and communication technologies. Graduates are equipped for roles in electronics, automation, and energy systems.`,
},
{
  id: 83,
  title: 'Master of Technology (M.Tech) in Mechanical Engineering',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `The M.Tech in Mechanical Engineering covers advanced topics in thermodynamics, robotics, fluid mechanics, and material science. Graduates pursue careers in automotive, aerospace, manufacturing, and research.`,
},
{
  id: 84,
  title: 'Master of Computer Applications (MCA)',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program focuses on software development, database management, and computer networks. It prepares students for technical and managerial roles in the IT sector, including software engineering and system architecture.`,
},
{
  id: 85,
  title: 'Master of Engineering (M.Eng) in Civil Engineering',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program provides advanced knowledge of structural engineering, construction management, and environmental engineering. Graduates are prepared for leadership positions in infrastructure development and civil engineering projects.`,
},
{
  id: 86,
  title: 'Master of Technology (M.Tech) in Artificial Intelligence',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `This program focuses on the study of artificial intelligence algorithms, machine learning, and data analytics. Graduates are equipped for careers in AI research, robotics, and data-driven decision making.`,
},
{
  id: 87,
  title: 'Master of Technology (M.Tech) in Data Science',
  category: 'Masters/PhD',
  duration: "2 years",
  img: '../Logo.png',
  desc: `The M.Tech in Data Science focuses on advanced data analytics, big data, and machine learning techniques. Graduates are prepared to analyze large datasets and provide actionable insights for businesses and research organizations.`,
},
{
  id: 88,
  title: 'Doctor of Philosophy in Computer Science (Ph.D.-CS)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `The Ph.D. program in Computer Science involves research in areas like software engineering, algorithms, AI, and cybersecurity. Graduates often work as researchers, professors, or leaders in the tech industry.`,
},
{
  id: 89,
  title: 'Doctor of Philosophy in Electrical Engineering (Ph.D.-EE)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `The Ph.D. in Electrical Engineering focuses on cutting-edge research in areas such as telecommunications, power systems, and embedded systems. Graduates can work in academia, research labs, or high-tech industries.`,
},
{
  id: 90,
  title: 'Doctor of Philosophy in Mechanical Engineering (Ph.D.-ME)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `This program focuses on research in areas like robotics, material science, and fluid dynamics. Graduates are prepared for high-level positions in academia, research, and engineering industries.`,
},
{
  id: 91,
  title: 'Doctor of Philosophy in Civil Engineering (Ph.D.-CE)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `The Ph.D. in Civil Engineering involves research in construction materials, structural analysis, and environmental engineering. Graduates contribute to infrastructure development and academic research in civil engineering.`,
},
{
  id: 92,
  title: 'Doctor of Philosophy in Artificial Intelligence (Ph.D.-AI)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `This program focuses on advanced research in artificial intelligence, including deep learning, machine learning, and cognitive computing. Graduates can lead AI research teams in academia or industry.`,
},
{
  id: 93,
  title: 'Doctor of Philosophy in Data Science (Ph.D.-DS)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `The Ph.D. in Data Science involves extensive research in data analytics, machine learning, and big data technologies. Graduates contribute to the advancement of data science in academia or high-level industries.`,
},
{
  id: 94,
  title: 'Doctor of Philosophy in Information Technology (Ph.D.-IT)',
  category: 'Masters/PhD',
  duration: "3-5 years",
  img: '../Logo.png',
  desc: `The Ph.D. in IT focuses on research in areas like software development, cybersecurity, database management, and systems architecture. Graduates typically pursue careers in academia, research, or IT consulting.`,
}

  
];
export default menu;
